#!/bin/sh -eux

cd "$RUN_DIR"

rm build/* -rf

# server build
npx rollup -c rollup.server.config.js
cp -r src/config_data build/server/

# frontend build
# npx vue-tsc --noEmit
npx vite build --config vite.config.js
