#!/bin/sh -ex

rm build/* -rf

# server build
npm run rollup -- -c rollup.server.config.js
cp -r src/templates build/server/

# frontend build
npm run vite -- build --config vite.config.js

# widgets build
npm run vite -- build --config widget-drawcast_draw.vite.config.js
npm run vite -- build --config widget-sr.vite.config.js
npm run vite -- build --config widget-media.vite.config.js
