#!/bin/sh

export APP_CONFIG=config.json
nodemon \
  --delay 2 \
  -x "node --experimental-specifier-resolution=node --loader ts-node/esm" \
  --max-old-space-size=256 \
  -w src \
  src/bot.ts \
  -e ts \
  --trace-warnings \
  --ignore public/static/
