#!/bin/env node

const verbose = !process.argv.includes('--silent')

const config = require('../src/config.js')
const Db = require('../src/Db.js')

const db = new Db(config.db)
db.patch(verbose)
db.close()
