name: ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  RUN_ENV: ci

jobs:
  tests:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ubuntu-latest, windows-latest]
        node-version: [20.x]
    name: "tests, node: ${{ matrix.node-version }}, os: ${{ matrix.operating-system }}"

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - run: npm ci
    - run: npm test -- run

  lint:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ubuntu-latest, windows-latest]
        node-version: [20.x]
    name: "lint, node: ${{ matrix.node-version }}, os: ${{ matrix.operating-system }}"

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - run: npm ci
    - run: npm run lint

  build:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ubuntu-latest, windows-latest]
        node-version: [20.x]
    name: "build, node: ${{ matrix.node-version }}, os: ${{ matrix.operating-system }}"

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - run: npm ci
    - run: npm run build
